//! Saved frames: bytes written by THIS build must still open on a LATER one,
//! and a LATER build's frame must still open on this one.
//!
//! # The codec boundary a fixture is saved at
//!
//! `tests/peer_wire.rs`'s `a_frame_round_trips_and_a_short_buffer_asks_for_more`
//! already covers `encode_frame`/`decode_frame`: a `u16` length prefix around
//! whatever bytes it is given, with no field of its own and nothing in it
//! that changes as a message type grows a field. Fixturing that layer would
//! prove nothing an older build could ever get wrong. What DOES change
//! release to release is the JSON payload inside the frame, so every fixture
//! here is that payload's exact UTF-8 text: what a peer's Noise session
//! decrypts into before `serde_json` ever sees it. A byte-for-byte capture
//! of an encoded frame would be this same text with four more bytes glued on
//! the front, and reading it back would still mean stripping those four
//! bytes and handing the rest to `serde_json`, so the JSON text is the
//! payload this crate's forward-compatibility promise is actually about.
//!
//! # Every fixture here was written by the build in this worktree
//!
//! Each one is hand-composed to match a real value (never regenerated by
//! calling `serde_json::to_string` and saving the output: a fixture
//! produced that way proves only that this build agrees with itself). Every
//! address is inside a documentation range (RFC 5737 `192.0.2.0/24` and
//! `198.51.100.0/24`); every id, key and hash is an obviously fake
//! placeholder.
//!
//! # What "the version bumped past the one this build reads" means here
//!
//! Every field this crate might one day add already has `#[serde(default)]`,
//! so the wire crate's own struct types have nothing that a bumped VALUE
//! (as opposed to a bumped SHAPE) can make them refuse: a `Hello.proto` of
//! 99 still decodes, because the parse's job is to survive a newer build,
//! never to police one (see the crate's own module docs: "the PARSE never
//! fails on a value a newer build invented. The unknown arm keeps the parse
//! alive; the HANDLER refuses it"). The one place that sentence is backed by
//! a real, already-wired handler reachable without standing up a Noise
//! session is `StreamKind`: `peer_stream_gate_rows` (`src/peer/listener.rs`)
//! refuses an unknown stream kind by name, with `StreamRefusal::UnknownKind`,
//! before it ever reads a grant. `stream_header_unknown_kind.json` fixtures a
//! `StreamHeader` naming a kind number no build has assigned, standing in for
//! a stream kind a future release invents: the parse survives it and the
//! typed refusal, not a panic, is what stops it.

use tcr_peer_wire::{
    Caps, Hello, InstanceId, Knock, Lease, LeaseGrant, LeaseReceipt, LeaseRefusal, LeaseRequest,
    LeaseUnit, Lendable, NeighborBrief, PeerId, StreamHeader, StreamKind, Window,
};
use teamclaude_rs::peer::listener::{peer_stream_gate_rows, StreamRefusal};

/// `tests/fixtures/wire/<name>`, read as UTF-8 text.
fn fixture(name: &str) -> String {
    std::fs::read_to_string(
        concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/wire/").to_string() + name,
    )
    .unwrap_or_else(|err| panic!("fixture {name} is readable: {err}"))
}

fn node_b() -> PeerId {
    PeerId::parse("QEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXVQEXG")
        .expect("fixture node id b decodes")
}

fn node_c() -> PeerId {
    PeerId::parse("SK6CSK6CSK6CSK6CSK6CSK6CSK6CSK6CSK6CSK6CSK6CSK6CSK60")
        .expect("fixture node id c decodes")
}

/// A `Hello` with every optional field populated decodes to the exact value
/// this build wrote, byte for byte, field for field.
///
/// Watch it fail: change `"seq":42` to `"seq":43` in the fixture and this
/// assertion reports a mismatched `Hello`, not a panic.
#[test]
fn hello_full_decodes_to_the_expected_value() {
    let hello: Hello = serde_json::from_str(&fixture("hello_full.json"))
        .expect("hello_full.json decodes as a Hello");
    assert_eq!(
        hello,
        Hello {
            proto: 1,
            node: node_b(),
            label: "laptop-full".to_string(),
            seq: 42,
            caps: Caps {
                egress: true,
                forward: true,
                lends: true,
            },
            addrs: vec![
                "192.0.2.10:9600".to_string(),
                "198.51.100.20:9600".to_string()
            ],
            ttl_s: 60,
            lendable: Some(vec![Lendable {
                window: Window::FiveHour,
                unit: LeaseUnit::Fraction(0.25),
                accounts: 2,
            }]),
            hops_to_egress: Some(1),
            briefs: Some(vec![NeighborBrief {
                node: node_c(),
                caps: Caps {
                    egress: false,
                    forward: true,
                    lends: false,
                },
                addrs: vec!["198.51.100.21:9600".to_string()],
            }]),
            build_sha: Some("deadbeefcafef00d".to_string()),
            boot_id: Some(123_456_789),
            observed_you_at: Some("192.0.2.11:41000".to_string()),
        }
    );
}

/// The same message with every optional field absent, exactly as an older
/// build that has never heard of `lendable`, `briefs`, `buildSha`, `bootId`
/// or `observedYouAt` would write one.
///
/// Watch it fail: delete `"ttlS":30` from the fixture and `serde_json`
/// refuses the frame outright (`ttl_s` carries no default), which is a
/// different failure than a value mismatch and this test would report it as
/// one.
#[test]
fn hello_minimal_decodes_to_the_expected_value() {
    let hello: Hello = serde_json::from_str(&fixture("hello_minimal.json"))
        .expect("hello_minimal.json decodes as a Hello");
    assert_eq!(
        hello,
        Hello {
            proto: 1,
            node: node_b(),
            label: "laptop-min".to_string(),
            seq: 1,
            caps: Caps {
                egress: false,
                forward: false,
                lends: false,
            },
            addrs: vec![],
            ttl_s: 30,
            lendable: None,
            hops_to_egress: None,
            briefs: None,
            build_sha: None,
            boot_id: None,
            observed_you_at: None,
        }
    );
}

/// A field this build has never seen (`aNewFieldThisBuildHasNeverSeen`,
/// standing in for a key a later release adds) decodes and is ignored: the
/// value is identical to the same message without it.
///
/// Watch it fail: add `#[serde(deny_unknown_fields)]` to `Hello` and this
/// fixture, which a NEWER peer would send to an OLDER one on a mixed-build
/// LAN, is refused outright instead of read.
#[test]
fn hello_with_an_unknown_field_still_decodes_and_the_field_is_ignored() {
    let with_unknown: Hello = serde_json::from_str(&fixture("hello_unknown_field.json"))
        .expect("a frame with a field this build has never seen still decodes");
    let minimal: Hello = serde_json::from_str(&fixture("hello_minimal.json"))
        .expect("hello_minimal.json decodes as a Hello");
    assert_eq!(
        with_unknown, minimal,
        "an unrecognized key must be silently ignored, not change the decoded value"
    );
}

/// The instance id both knock fixtures were written with.
fn knocker_instance() -> InstanceId {
    InstanceId::parse("a1b2c3d4e5f60718").expect("fixture instance id decodes")
}

/// A `Knock` with both of its optional fields populated: a proposed name and
/// the port the knocker listens on, which is the port an Accept dials back to.
///
/// Watch it fail: change `"listenPort":7766` to `7755` in the fixture and this
/// assertion reports a mismatched `Knock`, which is the same mismatch a
/// responder would act on by dialling the wrong Mac.
#[test]
fn knock_full_decodes_to_the_expected_value() {
    let knock: Knock =
        serde_json::from_str(&fixture("knock_full.json")).expect("knock_full.json decodes");
    assert_eq!(
        knock,
        Knock {
            instance_id: knocker_instance(),
            proposed_name: Some("laptop-knocker".to_string()),
            wire_version: 1,
            listen_port: Some(7766),
        }
    );
}

/// The same message with every optional field absent, which is exactly what a
/// build from before `listenPort` existed writes: it decodes, and the missing
/// port arrives as `None` rather than failing the frame or inventing a number.
///
/// Watch it fail: give `listen_port` a `#[serde(default = …)]` that answers
/// `Some(7755)` in `crates/tcr-peer-wire/src/lib.rs`, which is the tempting
/// wrong fix, and this reports `Some(7755)` where the frame said nothing. That
/// guess is the defect the field exists to end: it is the port an answer used
/// to be dialled to whatever the far Mac was really listening on.
///
/// Removing the `default` is NOT the mutation, and it was the first one tried
/// here: serde reads a missing `Option` field as `None` on its own, so the
/// attribute changes no behaviour and the test stayed green through it.
#[test]
fn knock_minimal_decodes_with_no_listen_port() {
    let knock: Knock =
        serde_json::from_str(&fixture("knock_minimal.json")).expect("knock_minimal.json decodes");
    assert_eq!(
        knock,
        Knock {
            instance_id: knocker_instance(),
            proposed_name: None,
            wire_version: 1,
            listen_port: None,
        }
    );
}

/// A `Lease` with its one optional field (`until`, the lending's own end)
/// populated.
///
/// Watch it fail: change `"maxInflight":3` to `4` in the fixture.
#[test]
fn lease_full_decodes_to_the_expected_value() {
    let lease: Lease = serde_json::from_str(&fixture("lease_full.json"))
        .expect("lease_full.json decodes as a Lease");
    assert_eq!(
        lease,
        Lease {
            lease_id: 42,
            window: Window::SevenDay,
            unit: LeaseUnit::Fraction(0.4),
            granted_at_ms: 1_758_000_000_000,
            expires_at_ms: 1_758_000_300_000,
            spent: 0.1,
            max_inflight: 3,
            until: Some(1_758_003_600),
        }
    );
}

/// The same lease with `until` absent: no end to the lending itself, which
/// is the default an operator gets by not asking for one, and the shape
/// every lease had before the field existed.
///
/// Watch it fail: change `"spent":0.1` to `0.2` in the fixture.
#[test]
fn lease_minimal_decodes_to_the_expected_value() {
    let lease: Lease = serde_json::from_str(&fixture("lease_minimal.json"))
        .expect("lease_minimal.json decodes as a Lease");
    assert_eq!(
        lease,
        Lease {
            lease_id: 42,
            window: Window::SevenDay,
            unit: LeaseUnit::Fraction(0.4),
            granted_at_ms: 1_758_000_000_000,
            expires_at_ms: 1_758_000_300_000,
            spent: 0.1,
            max_inflight: 3,
            until: None,
        }
    );
}

/// `LeaseRequest` carries no optional field, so one fixture is the whole of
/// its forward-compat surface.
///
/// Watch it fail: change `"maxInflight":2` to `3` in the fixture.
#[test]
fn lease_request_decodes_to_the_expected_value() {
    let request: LeaseRequest = serde_json::from_str(&fixture("lease_request.json"))
        .expect("lease_request.json decodes as a LeaseRequest");
    assert_eq!(
        request,
        LeaseRequest {
            window: Window::FiveHour,
            unit: LeaseUnit::Tokens(5_000),
            ttl_s: 300,
            max_inflight: 2,
        }
    );
}

/// A grant: `lease` present, `refusal` absent, the branch a borrower reads as
/// "here is your budget".
///
/// Watch it fail: change `"maxInflight":3` to `4` inside the nested lease.
#[test]
fn lease_grant_granted_decodes_to_the_expected_value() {
    let grant: LeaseGrant = serde_json::from_str(&fixture("lease_grant_granted.json"))
        .expect("lease_grant_granted.json decodes as a LeaseGrant");
    assert_eq!(
        grant,
        LeaseGrant {
            lease: Some(Lease {
                lease_id: 42,
                window: Window::SevenDay,
                unit: LeaseUnit::Fraction(0.4),
                granted_at_ms: 1_758_000_000_000,
                expires_at_ms: 1_758_000_300_000,
                spent: 0.1,
                max_inflight: 3,
                until: Some(1_758_003_600),
            }),
            refusal: None,
        }
    );
}

/// A refusal: `lease` absent, `refusal` present, the other branch the same
/// type carries.
///
/// Watch it fail: change `"too-many-leases"` to `"owner-guard"` in the
/// fixture.
#[test]
fn lease_grant_refused_decodes_to_the_expected_value() {
    let grant: LeaseGrant = serde_json::from_str(&fixture("lease_grant_refused.json"))
        .expect("lease_grant_refused.json decodes as a LeaseGrant");
    assert_eq!(
        grant,
        LeaseGrant {
            lease: None,
            refusal: Some(LeaseRefusal::TooManyLeases),
        }
    );
}

/// A `LeaseReceipt`: opaque lease id, opaque request id, a spend figure, and
/// nothing else, so one fixture is again the whole of its forward-compat
/// surface.
///
/// Watch it fail: change `"spent":0.05` to `0.06` in the fixture.
#[test]
fn lease_receipt_decodes_to_the_expected_value() {
    let receipt: LeaseReceipt = serde_json::from_str(&fixture("lease_receipt.json"))
        .expect("lease_receipt.json decodes as a LeaseReceipt");
    assert_eq!(
        receipt,
        LeaseReceipt {
            lease_id: 42,
            request_id: 777,
            spent: 0.05,
        }
    );
}

/// A stream naming a kind number no build has assigned yet still parses (the
/// crate's own promise: an unknown arm keeps a mixed-build LAN's parse
/// alive), and the production handler, not a panic, is what refuses it.
///
/// Watch it fail two ways, both run by hand before this shipped: (a) change
/// `"kind":9999` to `"kind":1` (`StreamKind::Tunnel`) and the assertion on
/// the parsed value fails, because the fixture no longer names an unknown
/// kind; (b) comment out the `StreamKind::Unknown(_)` arm in
/// `crates/tcr-peer-wire/src/lib.rs`'s `From<u16> for StreamKind` so it
/// cannot represent 9999 at all, and `serde_json::from_str` itself fails
/// this test rather than reaching the handler assertion: the parse-survives
/// half breaks before the refuse half is ever exercised.
#[test]
fn stream_header_with_an_unassigned_kind_parses_and_is_refused_by_the_handler_not_a_panic() {
    let header: StreamHeader = serde_json::from_str(&fixture("stream_header_unknown_kind.json"))
        .expect("a stream header naming an unassigned kind still parses");
    assert_eq!(
        header,
        StreamHeader {
            kind: StreamKind::Unknown(9999),
            target: None,
            via: vec![],
            hops_remaining: 1,
            request_id: 1001,
        }
    );
    assert_eq!(
        peer_stream_gate_rows(&header, None),
        Err(StreamRefusal::UnknownKind(9999)),
        "the handler must refuse an unknown kind by name, before it ever reads a grant, and \
         must not panic reaching that refusal"
    );
}
