import AppKit
import SwiftUI
import TcrBarCore

/// The one place a colour, a metric or a type size is written down.
///
/// ## Where these values come from
///
/// The palette is not hand-picked. It is authored in OKLCH — a perceptually
/// uniform space, so equal lightness steps read as equal brightness steps and a
/// hue does not drift as it darkens — and generated by
/// `scripts/tcrbar-palette.py`, which converts every colour to sRGB, rejects
/// anything outside the gamut, and measures WCAG contrast against the surface it
/// is actually drawn on. That script exits non-zero when a token fails.
///
/// That exit code is wired to a gate that can block a merge: the `ci` job in
/// `.github/workflows/ci.yml` runs the generator on every pull request, and `ci`
/// is a required check on `main`. So a bad colour fails a build rather than
/// being a matter of taste. Be precise about what "bad" means there — the script
/// measures WCAG contrast for every token against both surfaces it is drawn on,
/// rejects sRGB gamut clipping, and enforces a luminance floor between the pairs
/// that must not read alike; the two Increased Contrast passes cover ink only,
/// because the status hues already clear that bar in the normal passes. The same
/// CI step regenerates `apps/macos/design-tokens/` and diffs it, so a palette
/// edit that is never regenerated fails too. Nothing anywhere measures whether a
/// colour is the *right* colour.
///
/// The pre-commit hook in `.githooks/` runs the same check, but is a convenience
/// rather than the gate: it fires only when a token source is staged, skips with
/// a warning where `python3` is absent, and yields to `--no-verify`.
///
/// Two things it caught that eyeballing did not:
///
///  - The first draft had `ready` and `near` at a measured **1.00:1** — the same
///    brightness. On screen they were obviously green and amber; in greyscale, or
///    to a viewer with a red-green colour vision deficiency, "has headroom" and
///    "nearly exhausted" were the same pixel. Statuses are now separated in
///    *lightness*, not only hue, so urgency survives with no colour at all.
///  - A light palette derived by mechanically flipping the dark one put `ready`
///    and `spent` 1.07:1 apart, collapsing the worst pair for colour vision
///    deficiency. The light ramp is solved independently
///    (`scripts/solve-light-status.py`), not mirrored.
///
/// ## Why every token is dynamic
///
/// These replaced system semantic colours (`.green`, `.secondary`,
/// `.windowBackgroundColor`), which adapt to light mode and Increased Contrast
/// for free. A fixed palette that throws that away is a regression, so each token
/// carries four values — dark, light, and a high-contrast variant of each — and
/// all four are measured by the same script.
public enum Tok {

    // MARK: - Appearance-aware plumbing

    /// A colour that answers to the current appearance *and* the Increased
    /// Contrast setting, the way a system semantic colour does.
    ///
    /// Split from ``dyn`` because one token is needed as an `NSColor` as well:
    /// the menu-bar mark is built as an `NSImage` so it can opt out of template
    /// rendering, and a symbol configuration takes `NSColor`. Deriving the
    /// `Color` from the `NSColor` rather than writing the hexes twice is what
    /// stops the panel and the menu bar drifting apart.
    private static func dynNS(
        dark: String,
        light: String,
        darkHC: String? = nil,
        lightHC: String? = nil
    ) -> NSColor {
        NSColor(name: nil) { appearance in
            let matched = appearance.bestMatch(from: [
                .aqua, .darkAqua,
                .accessibilityHighContrastAqua,
                .accessibilityHighContrastDarkAqua,
            ])
            switch matched {
            case .accessibilityHighContrastDarkAqua:
                return NSColor(tokenHex: darkHC ?? dark)
            case .accessibilityHighContrastAqua:
                return NSColor(tokenHex: lightHC ?? light)
            case .darkAqua:
                return NSColor(tokenHex: dark)
            default:
                return NSColor(tokenHex: light)
            }
        }
    }

    private static func dyn(
        dark: String,
        light: String,
        darkHC: String? = nil,
        lightHC: String? = nil
    ) -> Color {
        Color(nsColor: dynNS(dark: dark, light: light, darkHC: darkHC, lightHC: lightHC))
    }

    // MARK: - Surfaces
    //
    // A near-neutral ramp at one cool hue. Chroma is deliberately tiny rather
    // than zero: a pure grey panel reads dead beside macOS's own chrome, while
    // anything much higher starts to look tinted.

    /// Backdrop behind the panel.
    public static let void = dyn(dark: "#090c10", light: "#f9fafb")
    /// The panel body.
    public static let panel = dyn(dark: "#13161b", light: "#f2f3f5")
    /// Account rows and cards.
    public static let raised = dyn(dark: "#1d2126", light: "#e8eaec")
    /// Row hover.
    public static let hover = dyn(dark: "#272c32", light: "#dbdee2")
    /// The empty part of a quota bar.
    public static let track = dyn(dark: "#2f3339", light: "#d2d4d8")
    /// 0.5pt dividers.
    public static let hairline = dyn(dark: "#393e43", light: "#c5c7cb")
    /// An emphasised divider or border.
    public static let hairlineStrong = dyn(dark: "#535960", light: "#a1a5aa")

    /// The v4 sheet's card fill (`docs/design/panel-tabs-mockup.html`,
    /// `data/plans/v4-spec.md`'s `rgba(255,255,255,.045)` over the panel) —
    /// an alias for `raised`, not a new colour: this ramp's own steps are
    /// each +0.045 L already (see the file's OKLCH source), which is the
    /// exact lift a 4.5%-white overlay on this panel produces. Naming it
    /// `cardFill` is for the v4 vocabulary; the value was already gated.
    public static let cardFill = raised
    /// The v4 sheet's card border / divider colour (`rgba(255,255,255,.09)`)
    /// — an alias for `hairline`, the token this file already uses for
    /// exactly that role ("0.5pt dividers").
    public static let cardLine = hairline

    /// The system accent stays a system colour: it is the user's choice, and
    /// overriding it would be this app asserting a preference it does not own.
    public static let accent = Color(nsColor: .controlAccentColor)

    // MARK: - Ink
    //
    // Warm-neutral off-white on dark, never pure white — pure white on a dark
    // panel vibrates. Increased Contrast pushes each step toward the extreme.

    /// Primary text. 16.1:1 on the dark panel, 17.0:1 on light.
    public static let ink = dyn(
        dark: "#f2f2ef", light: "#12120f", darkHC: "#ffffff", lightHC: "#040302")
    /// Secondary text. 9.7:1 dark, 8.3:1 light.
    public static let inkDim = dyn(
        dark: "#bfbeb9", light: "#494843", darkHC: "#d8d7d4", lightHC: "#2a2926")
    /// Tertiary text and hints. Still clears AA at 5.8:1 dark, 4.8:1 light.
    public static let inkFaint = dyn(
        dark: "#94928d", light: "#62605a", darkHC: "#b8b7b3", lightHC: "#494843")

    /// The v4 sheet's `dim` (secondary: `repo · model`, quota grid, metric
    /// line) — an alias for `inkDim`. The sheet's own hex (`#bfbfc7`) is a
    /// hair off `inkDim`'s (`#bfbeb9`), not enough to justify a second,
    /// separately-gated value for a role this ramp already covers at 9.7:1.
    public static let dim = inkDim
    /// The v4 sheet's `mute` (tertiary: plan line, section heads, footer,
    /// freshness) — an alias for `inkFaint`, for the same reason `dim` above
    /// aliases `inkDim`: the sheet's `#9a9aa3` is close to `inkFaint`'s
    /// `#94928d`, and `inkFaint` already clears AA (5.8:1) where the
    /// mockup's own `--mute` review note found the sheet's raw value did not.
    public static let mute = inkFaint

    // MARK: - Status
    //
    // Ordered by severity in LIGHTNESS as well as hue, so the panel still reads
    // in greyscale and to a viewer who cannot separate red from green.

    /// In rotation with headroom.
    public static let ok = dyn(dark: "#66d081", light: "#00873c")
    /// Close to a gating limit.
    public static let near = dyn(dark: "#ffd16b", light: "#ba7702")
    /// Spent on a gating window until it resets.
    public static let spent = dyn(dark: "#ea5a56", light: "#c0041f")
    /// Enabled, but nothing has ever been measured about it.
    ///
    /// Its own hue for the same reason `FleetTally.Kind.unmeasured` is its own
    /// bucket: `ok` would overclaim capacity, `spent` would claim an exhaustion
    /// nobody observed. Low chroma on purpose — an absent reading is not an
    /// alarm, so it must not sit on the traffic-light scale at all.
    public static let unmeasured = dyn(dark: "#82bad5", light: "#4c829c")
    /// Operator-disabled: a decision, not an alarm.
    public static let disabled = dyn(dark: "#909295", light: "#7f8083")
    /// A value this build cannot classify. Distinct from `unmeasured`: "a state
    /// I cannot name" is not "no state at all".
    public static let unknown = dyn(dark: "#c69bdd", light: "#7d4d96")
    /// Numbers that are structurally zero rather than measured.
    public static let offline = inkFaint

    /// Keep-awake mode is held.
    ///
    /// Its own hue, and specifically NOT `ok` / `near` / `spent`: those three
    /// are quota semantics, so an amber menu-bar mark would read as "the fleet
    /// is nearly exhausted" while actually meaning "this Mac will not idle
    /// sleep". Cyan is the open slot — hue 195, between `ok` at 150 and
    /// `unmeasured` at 230.
    ///
    /// Generated and gated like the rest of the palette
    /// (`scripts/tcrbar-palette.py`): dark `oklch(0.830 0.120 195)` measures
    /// **11.22:1** on the panel and **10.06:1** on a raised row; light
    /// `oklch(0.500 0.085 195)` measures **5.20:1** and **4.75:1**. Both clear
    /// their floor (4.5:1 dark, 3:1 light for a non-text element) and neither
    /// clips the sRGB gamut. It is held **1.31:1** dark / **1.37:1** light apart
    /// in luminance from `unmeasured`, the only other cool token, so the two do
    /// not collapse in greyscale.
    ///
    /// Every one of those figures is measured **against the panel**. The
    /// menu-bar mark is drawn on the wallpaper, where no contrast ratio can be
    /// guaranteed against anything — which is exactly why the menu bar carries
    /// this state as a glyph that is *present or absent* and uses colour only as
    /// a second channel. See `KeepAwakeGlyph`.
    public static let awakeNSColor = dynNS(dark: "#51dfdf", light: "#017272")
    public static let awake = Color(nsColor: awakeNSColor)

    /// The tint behind a status pill, and the hairline around it.
    public static func wash(_ tint: Color) -> Color { tint.opacity(0.14) }
    /// 0.40, not 0.34 as of the v4 pill restyle (`data/plans/v4-spec.md`'s
    /// pill border, ".35 (ok) / .40 (warn, bad)") — this helper has no
    /// per-role signal to pick between the two (`StatusPill`/`GroupChip`
    /// take a plain `Color`, not a status enum, and giving them one would
    /// mean changing every call site in `FleetView.swift`, out of scope
    /// here), so it is pinned to the sheet's more visible value rather than
    /// its softer one.
    public static func line(_ tint: Color) -> Color { tint.opacity(0.40) }

    /// The three status-dot colours the panel lane's fleet summary line
    /// draws (mockup `docs/design/panel-tabs-mockup.html`'s
    /// `.dot.busy`/`.dot.wait`/`.dot.idle`). Aliases, not new hues:
    /// `FleetView.swift:628-630` already maps busy/waiting/idle to these
    /// same three tokens, so the colours were already there — only the halo
    /// alpha below was missing.
    public static let statusBusy = ok
    public static let statusWaiting = near
    public static let statusIdle = inkFaint

    /// Alpha of the soft ring the mockup draws around a busy or waiting dot
    /// (`box-shadow: 0 0 0 3px rgba(_, .18)`). Its own token rather than a
    /// reuse of `wash`'s 0.14: a status dot's halo and a pill's background
    /// wash are two different elements that happen to share a rough shape,
    /// and tying them together would mean a change meant for one silently
    /// reaches the other.
    public static let statusHaloAlpha: CGFloat = 0.18
    /// The halo colour behind a status dot: the dot's own tint at
    /// `statusHaloAlpha`. Named apart from `wash`/`line` for the same reason
    /// the alpha above is its own token.
    public static func halo(_ tint: Color) -> Color { tint.opacity(statusHaloAlpha) }

    // MARK: - Type scale
    //
    // Named by ROLE, never by size, so a size change does not require renaming
    // every call site. This used to be a closed four-step scale — a principle
    // written before the v4 design existed, which does not veto the design: the
    // panel now follows the v4 sheet's own steps (`data/plans/v4-spec.md`'s
    // Type table), added below as their own roles rather than folded into the
    // four that follow, since `FleetView.swift` (a sibling lane's file) still
    // reaches for those four directly and a value change there needs its own
    // reviewed, rendered pass — not a redefinition slipped in under an old name.
    //
    // The floor is 10pt and it is used sparingly. An earlier density pass took
    // secondary text to 10pt and detail to 9pt, which is below every Apple
    // metric (`NSFont.smallSystemFontSize` is 11, `systemFontSize` is 13) and
    // below the readable floor for UI text. Fitting thirteen rows is not worth
    // text nobody can read; the panel scrolls instead.

    /// Panel title.
    public static let titleSize: CGFloat = 13
    /// The account name — the thing being scanned for. Never shrinks.
    public static let bodySize: CGFloat = 13
    /// Percentages, status text, the reset countdown.
    public static let secondaryFontSize: CGFloat = 11
    /// Counters, error detail, pill labels.
    public static let detailFontSize: CGFloat = 10

    public static var titleFont: Font { .system(size: titleSize, weight: .semibold) }
    public static var bodyFont: Font {
        .system(size: bodySize, design: .rounded).weight(.medium)
    }
    public static var secondaryFont: Font { .system(size: secondaryFontSize) }
    public static var detailFont: Font { .system(size: detailFontSize) }
    /// 10.5pt, weight 700 — the v4 pill restyle (`data/plans/v4-spec.md`'s
    /// pill row: "10.5 / 700 / +0.06em, uppercase"). Was 10pt/600; every
    /// rendered pill changes on purpose here, verified by re-reading
    /// `--render-states` PNGs, not a regression.
    public static var pillFont: Font {
        .system(size: pillFontSize, weight: .bold)
    }
    public static let pillFontSize: CGFloat = 10.5

    // MARK: - v4 sheet type roles
    //
    // `data/plans/v4-spec.md`'s Type table, added as their own named roles
    // rather than reusing `titleSize`/`bodySize`/`secondaryFontSize` above:
    // those four are still what `FleetView.swift` (a sibling lane's file)
    // reaches for today, and this lane does not touch that file, so a value
    // change there needs its own reviewed, rendered pass on that lane's own
    // schedule — these are what it picks up when it does. Tracking values are
    // the sheet's `em` figures converted to points at each role's own size
    // (`em * size`), since SwiftUI's `.tracking(_:)` takes points.

    /// Panel title `tcr fleet`. 17pt, 700, tracking -0.17pt (-0.01em).
    public static let panelTitleSize: CGFloat = 17
    public static let panelTitleTracking: CGFloat = -0.17
    public static var panelTitleFont: Font { .system(size: panelTitleSize, weight: .bold) }
    /// Freshness ("updated 4s ago") and the footer — the sheet gives both
    /// the same 12.5 / 400 / 0 / `mute`.
    public static let freshnessSize: CGFloat = 12.5
    public static var freshnessFont: Font { .system(size: freshnessSize) }
    public static var footerFont: Font { freshnessFont }
    /// Fleet summary line. 15pt, 400 (numbers 600), tracking 0.
    public static let summarySize: CGFloat = 15
    public static var summaryFont: Font { .system(size: summarySize) }
    public static var summaryNumberFont: Font { .system(size: summarySize, weight: .semibold) }
    /// Segmented tab label. 12.5pt, 600, tracking +0.25pt (+0.02em).
    public static let tabLabelSize: CGFloat = 12.5
    public static let tabLabelTracking: CGFloat = 0.25
    public static var tabLabelFont: Font { .system(size: tabLabelSize, weight: .semibold) }
    /// Account / session name — the thing being scanned for. 15pt, 600,
    /// tracking -0.075pt (-0.005em).
    public static let nameSize: CGFloat = 15
    public static let nameTracking: CGFloat = -0.075
    public static var nameFont: Font { .system(size: nameSize, weight: .semibold) }
    /// "Dim" line: `repo · model`, the quota grid. 13pt, 400.
    public static let dimLineSize: CGFloat = 13
    public static var dimLineFont: Font { .system(size: dimLineSize) }
    /// "Mute" line: the plan line. 12pt, 400.
    public static let muteLineSize: CGFloat = 12
    public static var muteLineFont: Font { .system(size: muteLineSize) }
    /// Section head. 11pt, 700, tracking +1.1pt (+0.1em), uppercase (applied
    /// at the call site the way `StatusPill`/`GroupChip` already uppercase).
    public static let sectionHeadSize: CGFloat = 11
    public static let sectionHeadTracking: CGFloat = 1.1
    public static var sectionHeadFont: Font { .system(size: sectionHeadSize, weight: .bold) }
    /// Command text. 12pt, SF Mono, 400.
    public static let monoSize: CGFloat = 12
    public static var monoFont: Font { .system(size: monoSize, design: .monospaced) }
    /// Button label. 13pt, 400. Geometry (`buttonRadius` etc.) is below with
    /// the rest of Space and geometry.
    public static let buttonFontSize: CGFloat = 13
    public static var buttonFont: Font { .system(size: buttonFontSize) }

    /// Explicit line height per size, one per role, so a 13pt row and an 11pt
    /// row are no longer spaced by two different, undeclared SwiftUI defaults
    /// — the inconsistency `wrappedLineSpacing` (below) never actually closed,
    /// since nothing calls it.
    ///
    /// SwiftUI has no line-height property; `.lineSpacing(_:)` adds spacing
    /// ABOVE a font's own single-line box, so the value applied at each call
    /// site is this line height minus the role's point size, not this number
    /// itself. That is an approximation — the font's true line box is a
    /// TextKit fact this file does not have — but it is one approximation
    /// applied identically everywhere the role is used, which is the
    /// consistency being asked for, not a claim of pixel-exact parity with any
    /// other app's rendering.
    public static let titleLineHeight: CGFloat = 18
    public static let bodyLineHeight: CGFloat = 18
    public static let secondaryLineHeight: CGFloat = 16
    public static let detailLineHeight: CGFloat = 14

    public static let titleLineSpacing: CGFloat = titleLineHeight - titleSize
    public static let bodyLineSpacing: CGFloat = bodyLineHeight - bodySize
    public static let secondaryLineSpacing: CGFloat = secondaryLineHeight - secondaryFontSize
    public static let detailLineSpacing: CGFloat = detailLineHeight - detailFontSize

    /// Tabular variants. Any value that CHANGES uses one of these: the panel
    /// re-polls every 3 seconds, and proportional digits make percentages and
    /// countdowns jitter their own column on every tick.
    public static var secondaryDigitFont: Font { secondaryFont.monospacedDigit() }
    public static var detailDigitFont: Font { detailFont.monospacedDigit() }
    public static var bodyDigitFont: Font { bodyFont.monospacedDigit() }

    /// Monospaced-digit variant of any font — for the panel lane to apply to
    /// every changing number, not only the three roles the named pairs above
    /// already cover.
    public static func tabular(_ font: Font) -> Font { font.monospacedDigit() }

    /// Positive tracking for the small pill labels. 0.63pt = the v4 sheet's
    /// +0.06em at `pillFontSize` (10.5) — was 0.3 at the old 10pt.
    public static let pillTracking: CGFloat = 0.63

    /// Line spacing for text that can wrap to three or more lines. Tight leading
    /// is for one-liners only.
    public static let wrappedLineSpacing: CGFloat = 2

    // MARK: - Space and geometry
    //
    // One 4pt-based ramp instead of scattered magic numbers.

    public static let space1: CGFloat = 2
    public static let space2: CGFloat = 4
    public static let space3: CGFloat = 8
    public static let space4: CGFloat = 12
    public static let space5: CGFloat = 16

    public static let panelWidth: CGFloat = 380
    /// The cap on the scrolling account list — what keeps Quit and the
    /// checkboxes on screen under a long fleet.
    ///
    /// A row count (`visibleAccountRows = 4`) used to do this and was the wrong
    /// unit: rows are not uniform height, so four of them is not a fixed number
    /// of points. `FleetView.visibleRowsHeight(for:)` sums every measured row
    /// and clamps here instead.
    ///
    /// It is the cap on the LIST, not on the panel, and 520 is what it stays: a
    /// header that wraps does not shrink this number, it spends part of it.
    /// The panel is `header + Hairline + list + Hairline + footer`, so a header
    /// line growing from one rendered line to three used to add that height on
    /// top of this cap and push Quit and the checkboxes off the bottom of the
    /// popover. `PanelHeight.listBudget` subtracts the header's overflow from
    /// this cap instead, which is what holds the panel's TOTAL height to what
    /// it was before the spend line existed.
    ///
    /// The number itself lives in `PanelHeight`, with the arithmetic that
    /// reads it, because the test target links `TcrBarCore` and not this one:
    /// stated here, the gate over that arithmetic could only assert against a
    /// hand-copied duplicate and would stay green through any change to it.
    /// It keeps its name over there, and `scripts/tcrbar-palette.py` reads
    /// that file as well as this one, so `--tcr-panel-max-height` is the same
    /// token it always was.
    public static let panelMaxHeight = PanelHeight.panelMaxHeight
    /// The floor under that budget: a header long enough to eat the whole cap
    /// must still leave a list a reader can scroll. A zero-height scroll view
    /// reads as a broken panel, not as a full one. Authored in `PanelHeight`
    /// for the reason above.
    public static let panelMinListHeight = PanelHeight.panelMinListHeight
    public static let gutter = space4
    public static let rowSpacing = space3
    /// Gap between two account cards. 14, not `rowSpacing` (8): the mockup
    /// (`docs/design/panel-tabs-mockup.html`) measures cards 2.3x farther
    /// apart than the rows inside one (`cardGap` / `rowGap` = 14 / 6).
    /// `rowSpacing` stays exactly as it was — a published alias for
    /// `space3` — so no existing call site has to change; the panel lane
    /// picks up `cardGap`/`rowGap` where it currently reaches for
    /// `rowSpacing`.
    public static let cardGap: CGFloat = 14
    /// Gap between the lines *inside* one account card. See `cardGap`.
    public static let rowGap: CGFloat = 6
    public static let tightSpacing = space2
    /// Gap between lines *inside* a row — tighter than the gap between rows, so
    /// a row still reads as one block.
    public static let rowLineSpacing = space1

    public static let radiusSmall: CGFloat = 8
    /// 16, which is what makes the account card concentric: its inset is
    /// `space3` (8) and the pills inside it are `pillRadius` (8), so the
    /// outer curve has to be inner + padding or the corners read pinched.
    public static let radiusMedium: CGFloat = 16
    public static let radiusLarge: CGFloat = 18
    /// Semantic alias for `radiusMedium`: the account card's own radius,
    /// named for the outer-equals-inner-plus-padding rule below rather than
    /// by its place on the point scale. Same value, so nothing already
    /// drawn moves; the panel lane reaches for this name, not `radiusMedium`.
    public static let cardRadius: CGFloat = radiusMedium
    /// The panel's inset beyond the card radius it encloses: `radiusLarge`
    /// (18) is `cardRadius` (16) plus this — the same
    /// outer-equals-inner-plus-padding rule `radiusMedium`'s own doc-comment
    /// above states for the card's pills one level in, and
    /// `groupOutlineRadius` below states for the group outline one level
    /// out. Published as its own token rather than folded into `radiusLarge`
    /// itself: `scripts/tcrbar-palette.py`'s `SWIFT_NUMERIC` regex matches
    /// only `= <number>`, so turning `radiusLarge` into an expression would
    /// silently drop `radius-large` out of `design-tokens/`.
    public static let cardPadding: CGFloat = 2
    public static let barHeight: CGFloat = 6
    /// 4, not 3 — matching the bump above. `RoundedRectangle` clamps its
    /// corner radius to half the shorter side (`CGPath(roundedRect:...)`'s own
    /// behaviour), and `barHeight` is 6, so this draws IDENTICALLY to 3: the
    /// value moved, the pixels did not. Left at the bridge's number anyway —
    /// it is still correct relative to `radiusSmall`/`radiusMedium` having
    /// moved — but the bar reading sharp is a `barHeight` fact, not a
    /// `barRadius` one, and `barHeight` is this panel's measured-row-height
    /// surface: out of scope for a token bump, flagged rather than changed.
    public static let barRadius: CGFloat = 4
    /// Width of a quota bar. Fixed, so the percentage after it starts at the
    /// same x on every card; a bar that took the leftover width could not.
    ///
    /// 72 is what fits. A row has about 300pt, and the 7-day line also carries
    /// `100%` (31), `in 4d 12h` (50) and the Fable weekly window,
    /// `fable 71% · in 4d 12h` (about 105). At 120 the trailing slot rendered
    /// truncated, at 80 it still did on the spent rows. A truncated figure
    /// deletes a measurement; a shorter bar only blunts a magnitude, and 72pt
    /// still resolves under a percent per pixel. The serving counters that used
    /// to hold that slot (`102 req · cache 84%`, 101) are a tooltip now — see
    /// `Account.countersTooltip(countersAreStructural:)`.
    public static let barWidth: CGFloat = 72
    /// Width of the `5h`/`7d` label. `5h` and `7d` are not the same width in a
    /// proportional face, so without this the two bars in a card start a hair
    /// apart.
    public static let windowLabelWidth: CGFloat = 20
    /// 7, its own literal as of the v4 pill restyle — no longer an alias for
    /// `radiusSmall` (8), which keeps its own value for its other consumers
    /// (the toggle backgrounds in `FleetView.swift`).
    public static let pillRadius: CGFloat = 7
    public static let pillPaddingH: CGFloat = 7
    public static let pillPaddingV: CGFloat = 2
    public static let hairlineWidth: CGFloat = 0.5

    /// The segmented-tab count badge (`data/plans/v4-spec.md`: "11pt on
    /// white .14, radius 9, padding 0 x 6"). Geometry only — the badge itself
    /// is drawn in `FleetView.swift` (a sibling lane's file), which picks
    /// these up on its own schedule the same way it does `cardGap`/`rowGap`.
    public static let tabBadgeFontSize: CGFloat = 11
    public static let tabBadgeRadius: CGFloat = 9
    public static let tabBadgePaddingH: CGFloat = 6
    public static let tabBadgePaddingV: CGFloat = 0
    /// `rgba(255,255,255,.14)` in the sheet — exactly `wash`'s existing 0.14
    /// alpha over `ink` (an off-white), so this reuses `wash(_:)` rather than
    /// adding a second alpha token for the same number.
    public static var tabBadgeBackground: Color { wash(ink) }

    /// Button (`data/plans/v4-spec.md`: "13pt, radius 7, min-height 28,
    /// padding 5 x 11"). Geometry only, for the same reason as the tab badge
    /// above — the button itself is drawn in `FleetView.swift`.
    public static let buttonRadius: CGFloat = 7
    public static let buttonMinHeight: CGFloat = 28
    public static let buttonPaddingH: CGFloat = 11
    public static let buttonPaddingV: CGFloat = 5

    /// Group outline: the section-level border wrapped around a named
    /// group's heading and rows (`docs/plans/group-outline-bridge.md`).
    /// Heavier than the card's own ``hairlineWidth`` (0.5) on purpose — a
    /// structural grouping cue drawn at arm's length needs to read at a
    /// glance, where a hairline disappears. Drawn at the section's OWN
    /// bounds (`FleetView.groupOutline(for:)`) with the section's CONTENT
    /// inset inward by `groupOutlineInset` on all four sides
    /// (`FleetView.sectionBody`) — an earlier version bled the stroke
    /// outward via negative padding instead, which only had room to survive
    /// vertically (inside the gap `rowSpacing` leaves between sections) and
    /// was clipped on the left and right, where the account list has no
    /// such gap. See `groupOutline(for:)`'s own doc-comment for the full
    /// account.
    public static let groupOutlineWidth: CGFloat = 1.0
    /// How far the section's content is inset from the stroke on every side.
    /// Kept under `rowSpacing` (8) for the same reason it always was — this
    /// used to bound how far the OLD outward bleed could travel before
    /// touching a neighbour; now it bounds how much the section visibly
    /// shrinks inside its own border, which reads better at a value smaller
    /// than the gap between two sections.
    public static let groupOutlineInset: CGFloat = 6
    /// Semantic alias for `groupOutlineInset`, named the way the panel lane
    /// asks for it — the group outline's own padding beyond the card radius
    /// it encloses. Same value as `groupOutlineInset`; not a second knob.
    public static let groupPadding: CGFloat = groupOutlineInset
    /// Bigger than `radiusMedium` (the cards' own radius) by roughly
    /// `groupOutlineInset` — the same outer-equals-inner-plus-padding rule
    /// `radiusMedium`'s own doc-comment uses for the cards, applied one
    /// level up so the outline reads as a looser box AROUND same-radius
    /// cards rather than a same-size sibling beside them.
    public static let groupOutlineRadius: CGFloat = radiusMedium + groupOutlineInset
    /// The legend's own height, in points — `detailFontSize` (10) plus its
    /// line-spacing plus the `space1` vertical breathing room the pill-style
    /// background around the text effectively adds. `FleetView.sectionBody`
    /// offsets the legend upward by half of this so it sits centred ON the
    /// stroke's top edge, the same way `HENRY-TOKEN · PARKED · 5` sits on
    /// the mockup's border rather than above or below it.
    public static let groupLegendHeight: CGFloat = detailFontSize + detailLineSpacing + space1

    // MARK: - Motion
    //
    // One duration and one curve for the whole app. A status panel that animates
    // in three different ways is noise, not polish. 0.15s and an ease-out
    // (`cubic-bezier(0, 0, .2, 1)`, the same curve `.easeOut` resolves to) are
    // the values measured off a competitor's compiled stylesheet, applied by
    // default there; bringing this panel's own single duration/curve pair up to
    // them is cheaper and more consistent than adding a second, faster pair
    // beside it.
    //
    // Every call site binds this to the SPECIFIC value that changed
    // (`.animation(_:value:)`), never a broad `withAnimation` at the poll site —
    // a 3-second poll that changes nothing must animate nothing — and every call
    // site honours `accessibilityReduceMotion`. Colour, opacity, bar fill and
    // pill presence only: never a property that changes a row's height, the
    // list's height or the panel's size — this panel's size is authored
    // (`panelWidth`) and its list height is the sum of measured row heights
    // (`FleetView.visibleRowsHeight(for:)`), and an animated height feeds that
    // measurement into a layout pass mid-animation, which is the layout-cycle
    // class `ffe8a86` already fixed once.

    public static let duration: TimeInterval = 0.15
    public static var standardAnimation: Animation {
        .easeOut(duration: duration)
    }

    // MARK: - Mapping

    public static func color(for state: QuotaState) -> Color {
        switch state {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        }
    }

    public static func color(for kind: FleetTally.Kind) -> Color {
        switch kind {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        // Reuses `spent`, not a new token: a broken account is known-cannot-
        // serve, the same certainty `spent` already carries, and this repo's
        // colour palette is generated — a new token drags in a regeneration
        // and two blocking gates for a fact this one already covers.
        case .needsRelogin: return spent
        case .unmeasured: return unmeasured
        case .disabled: return disabled
        }
    }

    /// Menu-bar glyph for the fleet's capacity state (`Fleet.capacityGlyphState`).
    /// SF Symbols only, so it renders as a template image and follows the menu
    /// bar's own tint.
    public static func glyph(for state: QuotaState) -> String {
        switch state {
        case .ok: return "gauge.with.dots.needle.33percent"
        case .near: return "gauge.with.dots.needle.67percent"
        case .spent: return "gauge.with.dots.needle.100percent"
        case .unknown: return "questionmark.circle"
        }
    }

    /// Glyph for a state where there is nothing to gauge.
    public static let unreadableGlyph = "exclamationmark.triangle"
}

// MARK: - Hex

extension NSColor {
    /// `#rrggbb`. Token colours are opaque; alpha is applied at the use site so
    /// a wash and its solid parent cannot drift apart.
    fileprivate convenience init(tokenHex hex: String) {
        var s = Substring(hex)
        if s.hasPrefix("#") { s = s.dropFirst() }
        let v = UInt32(s, radix: 16) ?? 0
        self.init(
            srgbRed: CGFloat((v >> 16) & 0xff) / 255,
            green: CGFloat((v >> 8) & 0xff) / 255,
            blue: CGFloat(v & 0xff) / 255,
            alpha: 1
        )
    }
}

// MARK: - Chrome

/// A status pill: a tinted label on a wash of its own hue, with a hairline.
///
/// Copy is stored in natural case and uppercased for display, so a wording change
/// never means rewriting the string, and tracking is applied because small text
/// set tight reads as crowded.
public struct StatusPill: View {
    private let text: String
    private let tint: Color

    /// Honour the system Reduce Motion setting, the way ``QuotaBar`` does.
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    public init(_ text: String, tint: Color) {
        self.text = text
        self.tint = tint
    }

    public var body: some View {
        Text(text.uppercased())
            .font(Tok.pillFont).lineSpacing(Tok.detailLineSpacing)
            .tracking(Tok.pillTracking)
            .foregroundStyle(tint)
            .padding(.horizontal, Tok.pillPaddingH)
            .padding(.vertical, Tok.pillPaddingV)
            .background(
                RoundedRectangle(cornerRadius: Tok.pillRadius)
                    .fill(Tok.wash(tint))
                    .overlay(
                        RoundedRectangle(cornerRadius: Tok.pillRadius)
                            .strokeBorder(Tok.line(tint), lineWidth: Tok.hairlineWidth)
                    )
            )
            .fixedSize()
            // Bound to `tint` alone: a row's band changing colour (ok -> near ->
            // spent) eases instead of snapping. The pill's size never depends on
            // `tint`, so nothing measured moves.
            .animation(reduceMotion ? nil : Tok.standardAnimation, value: tint)
    }
}

/// One group tag on an account row (``Account/groupTags``) — the whole
/// group-membership UI now that the dedicated Groups tab, deck cards and
/// section headers are gone (bridge: `docs/plans/group-tags-bridge.md`).
///
/// Tinted by the SERVER-resolved colour (``GroupTag/background``), never a
/// colour this app derives itself, so every client agrees on what a group
/// looks like. A missing or malformed colour (`nil`) falls back to
/// ``Tok/inkFaint`` — the same neutral hue ``StatusPill`` and this chip's own
/// prior, uncoloured version both already used — rather than guessing.
///
/// A reserved group is marked with a small lock glyph, not a colour or shape
/// change: colour is already spoken for by group identity here, so a second
/// meaning riding the same channel (filled vs. outlined, a different hue)
/// would ask the reader to disentangle two facts from one visual cue. The
/// glyph is a second, independent channel.
///
/// A PARKED group takes a pause glyph plus a dimmed wash of its own colour —
/// the hue still names the group, the dimming says "held back", and the two
/// glyphs stack for a group that is both. Dimming is used here and not for
/// `reserved` because parking is the stronger fact: a reserved group still
/// serves its own traffic, a parked one serves none.
public struct GroupChip: View {
    private let tag: GroupTag

    /// Honour the system Reduce Motion setting, the way ``QuotaBar`` does.
    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    public init(tag: GroupTag) {
        self.tag = tag
    }

    /// `nil` background (no wire colour) draws the neutral wash a plain
    /// `StatusPill` already uses; a real colour is drawn solid, since a
    /// translucent wash over an operator-chosen hue would mis-render the
    /// luminance ``foreground`` was computed against.
    private var background: Color {
        // A parked group is dimmed rather than recoloured: the hue still has to
        // say WHICH group this is, so the state rides opacity plus the glyph
        // below, two channels neither of which is the identity one. Applied to
        // the neutral fallback too — a colourless tag is exactly the case where
        // the reader has the least else to go on.
        let base = tag.background.map { Color(red: $0.red, green: $0.green, blue: $0.blue) }
        let solid = base ?? Tok.wash(Tok.inkFaint)
        return tag.isParked ? solid.opacity(Self.parkedOpacity) : solid
    }

    /// Enough to read as "held back" beside a live tag on the same row, not so
    /// little that the group's own colour stops being identifiable. Named
    /// rather than inlined because `background` and `border` must move
    /// together — two literals here would drift.
    private static let parkedOpacity: Double = 0.35

    private var border: Color {
        let base = tag.background.map {
            Color(red: $0.red, green: $0.green, blue: $0.blue).opacity(0.6)
        }
        let edge = base ?? Tok.line(Tok.inkFaint)
        return tag.isParked ? edge.opacity(Self.parkedOpacity) : edge
    }

    /// Chosen from the background's relative luminance
    /// (``GroupTagColor/isLight(_:)``), not hardcoded — these chips sit on a
    /// dark panel and the colour is operator-chosen, so a light pick (a pale
    /// yellow) needs dark text and a very dark pick needs light text, or
    /// either renders unreadable. `nil` background (the neutral fallback)
    /// uses ``Tok/ink``, the panel's own primary-text token, since that wash
    /// is already tuned against the dark panel the same way every other
    /// `StatusPill` is.
    private var foreground: Color {
        // A PARKED chip's fill is a dimmed wash of the group's hue, so the
        // black/white choice below — computed against the FULL-strength colour
        // — is the wrong answer for it: `#32d74b` is dark enough to ask for
        // white text, and at 35% over a light panel that white sat on a pale
        // green and was barely readable (caught in `15-parked-group-light.png`,
        // not by the type checker). A wash takes panel ink, exactly as the
        // no-colour fallback below already does.
        //
        // `ink`, not the secondary `inkDim`: measured off the rendered PNG,
        // `inkDim` on the dimmed dark-mode chip is 3.98:1, under AA for text
        // this small, while `ink` reads 6.5:1 dark and 12.9:1 light. The wash
        // is what says "held back"; the label still has to be readable.
        if tag.isParked { return Tok.ink }
        guard let rgb = tag.background else { return Tok.ink }
        return GroupTagColor.isLight(rgb) ? .black : .white
    }

    public var body: some View {
        HStack(spacing: 2) {
            if tag.isParked {
                // Its own glyph, drawn BEFORE the lock so the two read as two
                // facts when a group is both parked and reserved. A dimmed tag
                // alone would be ambiguous with an unresolved colour.
                Image(systemName: "pause.fill")
                    .font(.system(size: Tok.detailFontSize - 2, weight: .bold))
            }
            if tag.isReserved {
                Image(systemName: "lock.fill")
                    .font(.system(size: Tok.detailFontSize - 2, weight: .bold))
            }
            Text(tag.name.uppercased())
                .font(Tok.pillFont).lineSpacing(Tok.detailLineSpacing)
                .tracking(Tok.pillTracking)
        }
        .foregroundStyle(foreground)
        .padding(.horizontal, Tok.pillPaddingH)
        .padding(.vertical, Tok.pillPaddingV)
        .background(
            RoundedRectangle(cornerRadius: Tok.pillRadius)
                .fill(background)
                .overlay(
                    RoundedRectangle(cornerRadius: Tok.pillRadius)
                        .strokeBorder(border, lineWidth: Tok.hairlineWidth)
                )
        )
        .fixedSize()
        // Bound to `isParked`, the one state this chip's colour rides: it
        // dims rather than recolours, and the dim is what should ease in and
        // out. Size never depends on it, so nothing measured moves.
        .animation(reduceMotion ? nil : Tok.standardAnimation, value: tag.isParked)
        .help(
            tag.isParked
                // Said first and on its own: a parked group serves nothing at
                // all, so whether it is ALSO reserved changes nothing an
                // operator can act on right now.
                ? "\(tag.name) (parked — every member is out of rotation until "
                    + "`tcr group unpark \(tag.name)`)"
                : tag.isReserved
                    // Both directions, because half the sentence is how the pool-facing
                    // half got read as the whole feature: "held out of the general pool"
                    // says nothing about whether THIS group's traffic can wander off to
                    // another account, and it can't.
                    ? "\(tag.name) (reserved — pool traffic never uses this account, "
                        + "and --group \(tag.name) never serves from outside the group)"
                        // Named explicitly rather than left bare: a group tag with no lock is
                        // decoration, and reading it as isolation is what lets pool traffic
                        // sit on an account someone believed was private.
                    : "\(tag.name) (tagged only — not reserved, so pool traffic still "
                        + "uses this account and --group \(tag.name) may be served by another)"
        )
    }
}

/// A 0.5pt hairline. `Divider()` picks up the system separator, which no longer
/// matches this palette's ramp.
public struct Hairline: View {
    public init() {}
    public var body: some View {
        Rectangle()
            .fill(Tok.hairline)
            .frame(height: Tok.hairlineWidth)
    }
}
