import AppKit
import SwiftUI
import TcrBarCore

/// The one place a colour, a metric or a type size is written down.
///
/// ## Where these values come from
///
/// The palette is not hand-picked. It is authored in OKLCH — a perceptually
/// uniform space, so equal lightness steps read as equal brightness steps and a
/// hue does not drift as it darkens — and generated by
/// `scripts/tcrbar-palette.py`, which converts every colour to sRGB, rejects
/// anything outside the gamut, and measures WCAG contrast against the surface it
/// is actually drawn on. That script exits non-zero when a token fails, so a bad
/// colour is a build error rather than a matter of taste.
///
/// Two things it caught that eyeballing did not:
///
///  - The first draft had `ready` and `near` at a measured **1.00:1** — the same
///    brightness. On screen they were obviously green and amber; in greyscale, or
///    to a viewer with a red-green colour vision deficiency, "has headroom" and
///    "nearly exhausted" were the same pixel. Statuses are now separated in
///    *lightness*, not only hue, so urgency survives with no colour at all.
///  - A light palette derived by mechanically flipping the dark one put `ready`
///    and `spent` 1.07:1 apart, collapsing the worst pair for colour vision
///    deficiency. The light ramp is solved independently
///    (`scripts/solve-light-status.py`), not mirrored.
///
/// ## Why every token is dynamic
///
/// These replaced system semantic colours (`.green`, `.secondary`,
/// `.windowBackgroundColor`), which adapt to light mode and Increased Contrast
/// for free. A fixed palette that throws that away is a regression, so each token
/// carries four values — dark, light, and a high-contrast variant of each — and
/// all four are measured by the same script.
public enum Tok {

    // MARK: - Appearance-aware plumbing

    /// A colour that answers to the current appearance *and* the Increased
    /// Contrast setting, the way a system semantic colour does.
    private static func dyn(
        dark: String,
        light: String,
        darkHC: String? = nil,
        lightHC: String? = nil
    ) -> Color {
        Color(
            nsColor: NSColor(name: nil) { appearance in
                let matched = appearance.bestMatch(from: [
                    .aqua, .darkAqua,
                    .accessibilityHighContrastAqua,
                    .accessibilityHighContrastDarkAqua,
                ])
                switch matched {
                case .accessibilityHighContrastDarkAqua:
                    return NSColor(tokenHex: darkHC ?? dark)
                case .accessibilityHighContrastAqua:
                    return NSColor(tokenHex: lightHC ?? light)
                case .darkAqua:
                    return NSColor(tokenHex: dark)
                default:
                    return NSColor(tokenHex: light)
                }
            }
        )
    }

    // MARK: - Surfaces
    //
    // A near-neutral ramp at one cool hue. Chroma is deliberately tiny rather
    // than zero: a pure grey panel reads dead beside macOS's own chrome, while
    // anything much higher starts to look tinted.

    /// Backdrop behind the panel.
    public static let void = dyn(dark: "#090c10", light: "#f9fafb")
    /// The panel body.
    public static let panel = dyn(dark: "#13161b", light: "#f2f3f5")
    /// Account rows and cards.
    public static let raised = dyn(dark: "#1d2126", light: "#e8eaec")
    /// Row hover.
    public static let hover = dyn(dark: "#272c32", light: "#dbdee2")
    /// The empty part of a quota bar.
    public static let track = dyn(dark: "#2f3339", light: "#d2d4d8")
    /// 0.5pt dividers.
    public static let hairline = dyn(dark: "#393e43", light: "#c5c7cb")
    /// An emphasised divider or border.
    public static let hairlineStrong = dyn(dark: "#535960", light: "#a1a5aa")

    /// The system accent stays a system colour: it is the user's choice, and
    /// overriding it would be this app asserting a preference it does not own.
    public static let accent = Color(nsColor: .controlAccentColor)

    // MARK: - Ink
    //
    // Warm-neutral off-white on dark, never pure white — pure white on a dark
    // panel vibrates. Increased Contrast pushes each step toward the extreme.

    /// Primary text. 16.1:1 on the dark panel, 17.0:1 on light.
    public static let ink = dyn(
        dark: "#f2f2ef", light: "#12120f", darkHC: "#ffffff", lightHC: "#040302")
    /// Secondary text. 9.7:1 dark, 8.3:1 light.
    public static let inkDim = dyn(
        dark: "#bfbeb9", light: "#494843", darkHC: "#d8d7d4", lightHC: "#2a2926")
    /// Tertiary text and hints. Still clears AA at 5.8:1 dark, 4.8:1 light.
    public static let inkFaint = dyn(
        dark: "#94928d", light: "#62605a", darkHC: "#b8b7b3", lightHC: "#494843")

    // MARK: - Status
    //
    // Ordered by severity in LIGHTNESS as well as hue, so the panel still reads
    // in greyscale and to a viewer who cannot separate red from green.

    /// In rotation with headroom.
    public static let ok = dyn(dark: "#66d081", light: "#00873c")
    /// Close to a gating limit.
    public static let near = dyn(dark: "#ffd16b", light: "#ba7702")
    /// Spent on a gating window until it resets.
    public static let spent = dyn(dark: "#ea5a56", light: "#c0041f")
    /// Enabled, but nothing has ever been measured about it.
    ///
    /// Its own hue for the same reason `FleetTally.Kind.unmeasured` is its own
    /// bucket: `ok` would overclaim capacity, `spent` would claim an exhaustion
    /// nobody observed. Low chroma on purpose — an absent reading is not an
    /// alarm, so it must not sit on the traffic-light scale at all.
    public static let unmeasured = dyn(dark: "#82bad5", light: "#4c829c")
    /// Operator-disabled: a decision, not an alarm.
    public static let disabled = dyn(dark: "#909295", light: "#7f8083")
    /// A value this build cannot classify. Distinct from `unmeasured`: "a state
    /// I cannot name" is not "no state at all".
    public static let unknown = dyn(dark: "#c69bdd", light: "#7d4d96")
    /// Numbers that are structurally zero rather than measured.
    public static let offline = inkFaint

    /// The tint behind a status pill, and the hairline around it.
    public static func wash(_ tint: Color) -> Color { tint.opacity(0.14) }
    public static func line(_ tint: Color) -> Color { tint.opacity(0.34) }

    // MARK: - Type scale
    //
    // Named by ROLE, never by size, so a size change does not require renaming
    // every call site. Four steps is the whole scale — a status panel that needs
    // more is being over-designed.
    //
    // The floor is 10pt and it is used sparingly. An earlier density pass took
    // secondary text to 10pt and detail to 9pt, which is below every Apple
    // metric (`NSFont.smallSystemFontSize` is 11, `systemFontSize` is 13) and
    // below the readable floor for UI text. Fitting thirteen rows is not worth
    // text nobody can read; the panel scrolls instead.

    /// Panel title.
    public static let titleSize: CGFloat = 13
    /// The account name — the thing being scanned for. Never shrinks.
    public static let bodySize: CGFloat = 13
    /// Percentages, status text, the reset countdown.
    public static let secondaryFontSize: CGFloat = 11
    /// Counters, error detail, pill labels.
    public static let detailFontSize: CGFloat = 10

    public static var titleFont: Font { .system(size: titleSize, weight: .semibold) }
    public static var bodyFont: Font {
        .system(size: bodySize, design: .rounded).weight(.medium)
    }
    public static var secondaryFont: Font { .system(size: secondaryFontSize) }
    public static var detailFont: Font { .system(size: detailFontSize) }
    /// Weight 600 at 10pt. Nothing here goes below 400 — light weights vanish at
    /// UI sizes.
    public static var pillFont: Font {
        .system(size: detailFontSize, weight: .semibold)
    }

    /// Tabular variants. Any value that CHANGES uses one of these: the panel
    /// re-polls every 3 seconds, and proportional digits make percentages and
    /// countdowns jitter their own column on every tick.
    public static var secondaryDigitFont: Font { secondaryFont.monospacedDigit() }
    public static var detailDigitFont: Font { detailFont.monospacedDigit() }
    public static var bodyDigitFont: Font { bodyFont.monospacedDigit() }

    /// Positive tracking for the small pill labels. Small text set tight reads as
    /// crowded; a little air is what makes a 10pt label legible.
    public static let pillTracking: CGFloat = 0.3

    /// Line spacing for text that can wrap to three or more lines. Tight leading
    /// is for one-liners only.
    public static let wrappedLineSpacing: CGFloat = 2

    // MARK: - Space and geometry
    //
    // One 4pt-based ramp instead of scattered magic numbers.

    public static let space1: CGFloat = 2
    public static let space2: CGFloat = 4
    public static let space3: CGFloat = 8
    public static let space4: CGFloat = 12
    public static let space5: CGFloat = 16

    public static let panelWidth: CGFloat = 380
    public static let panelMaxHeight: CGFloat = 520
    public static let gutter = space4
    public static let rowSpacing = space3
    public static let tightSpacing = space2
    /// Vertical breathing room around one account row.
    public static let rowPaddingV = space1
    /// Gap between lines *inside* a row — tighter than the gap between rows, so
    /// a row still reads as one block.
    public static let rowLineSpacing = space1

    public static let radiusSmall: CGFloat = 4
    public static let radiusMedium: CGFloat = 8
    public static let radiusLarge: CGFloat = 12
    public static let barHeight: CGFloat = 6
    public static let barRadius: CGFloat = 3
    public static let pillRadius = radiusSmall
    public static let pillPaddingH: CGFloat = 6
    public static let pillPaddingV: CGFloat = 2
    public static let hairlineWidth: CGFloat = 0.5

    // MARK: - Motion
    //
    // One duration and one curve for the whole app. A status panel that animates
    // in three different ways is noise, not polish.

    public static let duration: TimeInterval = 0.22
    public static var standardAnimation: Animation {
        .timingCurve(0.22, 1, 0.36, 1, duration: duration)
    }

    // MARK: - Mapping

    public static func color(for state: QuotaState) -> Color {
        switch state {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        }
    }

    public static func color(for kind: FleetTally.Kind) -> Color {
        switch kind {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        case .unmeasured: return unmeasured
        case .disabled: return disabled
        }
    }

    /// Menu-bar glyph for the fleet's capacity state (`Fleet.capacityGlyphState`).
    /// SF Symbols only, so it renders as a template image and follows the menu
    /// bar's own tint.
    public static func glyph(for state: QuotaState) -> String {
        switch state {
        case .ok: return "gauge.with.dots.needle.33percent"
        case .near: return "gauge.with.dots.needle.67percent"
        case .spent: return "gauge.with.dots.needle.100percent"
        case .unknown: return "questionmark.circle"
        }
    }

    /// Glyph for a state where there is nothing to gauge.
    public static let unreadableGlyph = "exclamationmark.triangle"
}

// MARK: - Hex

extension NSColor {
    /// `#rrggbb`. Token colours are opaque; alpha is applied at the use site so
    /// a wash and its solid parent cannot drift apart.
    fileprivate convenience init(tokenHex hex: String) {
        var s = Substring(hex)
        if s.hasPrefix("#") { s = s.dropFirst() }
        let v = UInt32(s, radix: 16) ?? 0
        self.init(
            srgbRed: CGFloat((v >> 16) & 0xff) / 255,
            green: CGFloat((v >> 8) & 0xff) / 255,
            blue: CGFloat(v & 0xff) / 255,
            alpha: 1
        )
    }
}

// MARK: - Chrome

/// A status pill: a tinted label on a wash of its own hue, with a hairline.
///
/// Copy is stored in natural case and uppercased for display, so a wording change
/// never means rewriting the string, and tracking is applied because small text
/// set tight reads as crowded.
public struct StatusPill: View {
    private let text: String
    private let tint: Color

    public init(_ text: String, tint: Color) {
        self.text = text
        self.tint = tint
    }

    public var body: some View {
        Text(text.uppercased())
            .font(Tok.pillFont)
            .tracking(Tok.pillTracking)
            .foregroundStyle(tint)
            .padding(.horizontal, Tok.pillPaddingH)
            .padding(.vertical, Tok.pillPaddingV)
            .background(
                RoundedRectangle(cornerRadius: Tok.pillRadius)
                    .fill(Tok.wash(tint))
                    .overlay(
                        RoundedRectangle(cornerRadius: Tok.pillRadius)
                            .strokeBorder(Tok.line(tint), lineWidth: Tok.hairlineWidth)
                    )
            )
            .fixedSize()
    }
}

/// A 0.5pt hairline. `Divider()` picks up the system separator, which no longer
/// matches this palette's ramp.
public struct Hairline: View {
    public init() {}
    public var body: some View {
        Rectangle()
            .fill(Tok.hairline)
            .frame(height: Tok.hairlineWidth)
    }
}
