import AppKit
import SwiftUI
import TcrBarCore

/// The one place a colour, a metric or a type size is written down.
///
/// ## Where these values come from
///
/// The palette is not hand-picked. It is authored in OKLCH — a perceptually
/// uniform space, so equal lightness steps read as equal brightness steps and a
/// hue does not drift as it darkens — and generated by
/// `scripts/tcrbar-palette.py`, which converts every colour to sRGB, rejects
/// anything outside the gamut, and measures WCAG contrast against the surface it
/// is actually drawn on. That script exits non-zero when a token fails.
///
/// That exit code is wired to a gate that can block a merge: the `ci` job in
/// `.github/workflows/ci.yml` runs the generator on every pull request, and `ci`
/// is a required check on `main`. So a bad colour fails a build rather than
/// being a matter of taste. Be precise about what "bad" means there — the script
/// measures WCAG contrast for every token against both surfaces it is drawn on,
/// rejects sRGB gamut clipping, and enforces a luminance floor between the pairs
/// that must not read alike; the two Increased Contrast passes cover ink only,
/// because the status hues already clear that bar in the normal passes. The same
/// CI step regenerates `apps/macos/design-tokens/` and diffs it, so a palette
/// edit that is never regenerated fails too. Nothing anywhere measures whether a
/// colour is the *right* colour.
///
/// The pre-commit hook in `.githooks/` runs the same check, but is a convenience
/// rather than the gate: it fires only when a token source is staged, skips with
/// a warning where `python3` is absent, and yields to `--no-verify`.
///
/// Two things it caught that eyeballing did not:
///
///  - The first draft had `ready` and `near` at a measured **1.00:1** — the same
///    brightness. On screen they were obviously green and amber; in greyscale, or
///    to a viewer with a red-green colour vision deficiency, "has headroom" and
///    "nearly exhausted" were the same pixel. Statuses are now separated in
///    *lightness*, not only hue, so urgency survives with no colour at all.
///  - A light palette derived by mechanically flipping the dark one put `ready`
///    and `spent` 1.07:1 apart, collapsing the worst pair for colour vision
///    deficiency. The light ramp is solved independently
///    (`scripts/solve-light-status.py`), not mirrored.
///
/// ## Why every token is dynamic
///
/// These replaced system semantic colours (`.green`, `.secondary`,
/// `.windowBackgroundColor`), which adapt to light mode and Increased Contrast
/// for free. A fixed palette that throws that away is a regression, so each token
/// carries four values — dark, light, and a high-contrast variant of each — and
/// all four are measured by the same script.
public enum Tok {

    // MARK: - Appearance-aware plumbing

    /// A colour that answers to the current appearance *and* the Increased
    /// Contrast setting, the way a system semantic colour does.
    ///
    /// Split from ``dyn`` because one token is needed as an `NSColor` as well:
    /// the menu-bar mark is built as an `NSImage` so it can opt out of template
    /// rendering, and a symbol configuration takes `NSColor`. Deriving the
    /// `Color` from the `NSColor` rather than writing the hexes twice is what
    /// stops the panel and the menu bar drifting apart.
    private static func dynNS(
        dark: String,
        light: String,
        darkHC: String? = nil,
        lightHC: String? = nil
    ) -> NSColor {
        NSColor(name: nil) { appearance in
            let matched = appearance.bestMatch(from: [
                .aqua, .darkAqua,
                .accessibilityHighContrastAqua,
                .accessibilityHighContrastDarkAqua,
            ])
            switch matched {
            case .accessibilityHighContrastDarkAqua:
                return NSColor(tokenHex: darkHC ?? dark)
            case .accessibilityHighContrastAqua:
                return NSColor(tokenHex: lightHC ?? light)
            case .darkAqua:
                return NSColor(tokenHex: dark)
            default:
                return NSColor(tokenHex: light)
            }
        }
    }

    private static func dyn(
        dark: String,
        light: String,
        darkHC: String? = nil,
        lightHC: String? = nil
    ) -> Color {
        Color(nsColor: dynNS(dark: dark, light: light, darkHC: darkHC, lightHC: lightHC))
    }

    // MARK: - Surfaces
    //
    // A near-neutral ramp at one cool hue. Chroma is deliberately tiny rather
    // than zero: a pure grey panel reads dead beside macOS's own chrome, while
    // anything much higher starts to look tinted.

    /// Backdrop behind the panel.
    public static let void = dyn(dark: "#090c10", light: "#f9fafb")
    /// The panel body.
    public static let panel = dyn(dark: "#13161b", light: "#f2f3f5")
    /// Account rows and cards.
    public static let raised = dyn(dark: "#1d2126", light: "#e8eaec")
    /// Row hover.
    public static let hover = dyn(dark: "#272c32", light: "#dbdee2")
    /// The empty part of a quota bar.
    public static let track = dyn(dark: "#2f3339", light: "#d2d4d8")
    /// 0.5pt dividers.
    public static let hairline = dyn(dark: "#393e43", light: "#c5c7cb")
    /// An emphasised divider or border.
    public static let hairlineStrong = dyn(dark: "#535960", light: "#a1a5aa")

    /// The system accent stays a system colour: it is the user's choice, and
    /// overriding it would be this app asserting a preference it does not own.
    public static let accent = Color(nsColor: .controlAccentColor)

    // MARK: - Ink
    //
    // Warm-neutral off-white on dark, never pure white — pure white on a dark
    // panel vibrates. Increased Contrast pushes each step toward the extreme.

    /// Primary text. 16.1:1 on the dark panel, 17.0:1 on light.
    public static let ink = dyn(
        dark: "#f2f2ef", light: "#12120f", darkHC: "#ffffff", lightHC: "#040302")
    /// Secondary text. 9.7:1 dark, 8.3:1 light.
    public static let inkDim = dyn(
        dark: "#bfbeb9", light: "#494843", darkHC: "#d8d7d4", lightHC: "#2a2926")
    /// Tertiary text and hints. Still clears AA at 5.8:1 dark, 4.8:1 light.
    public static let inkFaint = dyn(
        dark: "#94928d", light: "#62605a", darkHC: "#b8b7b3", lightHC: "#494843")

    // MARK: - Status
    //
    // Ordered by severity in LIGHTNESS as well as hue, so the panel still reads
    // in greyscale and to a viewer who cannot separate red from green.

    /// In rotation with headroom.
    public static let ok = dyn(dark: "#66d081", light: "#00873c")
    /// Close to a gating limit.
    public static let near = dyn(dark: "#ffd16b", light: "#ba7702")
    /// Spent on a gating window until it resets.
    public static let spent = dyn(dark: "#ea5a56", light: "#c0041f")
    /// Enabled, but nothing has ever been measured about it.
    ///
    /// Its own hue for the same reason `FleetTally.Kind.unmeasured` is its own
    /// bucket: `ok` would overclaim capacity, `spent` would claim an exhaustion
    /// nobody observed. Low chroma on purpose — an absent reading is not an
    /// alarm, so it must not sit on the traffic-light scale at all.
    public static let unmeasured = dyn(dark: "#82bad5", light: "#4c829c")
    /// Operator-disabled: a decision, not an alarm.
    public static let disabled = dyn(dark: "#909295", light: "#7f8083")
    /// A value this build cannot classify. Distinct from `unmeasured`: "a state
    /// I cannot name" is not "no state at all".
    public static let unknown = dyn(dark: "#c69bdd", light: "#7d4d96")
    /// Numbers that are structurally zero rather than measured.
    public static let offline = inkFaint

    /// Keep-awake mode is held.
    ///
    /// Its own hue, and specifically NOT `ok` / `near` / `spent`: those three
    /// are quota semantics, so an amber menu-bar mark would read as "the fleet
    /// is nearly exhausted" while actually meaning "this Mac will not idle
    /// sleep". Cyan is the open slot — hue 195, between `ok` at 150 and
    /// `unmeasured` at 230.
    ///
    /// Generated and gated like the rest of the palette
    /// (`scripts/tcrbar-palette.py`): dark `oklch(0.830 0.120 195)` measures
    /// **11.22:1** on the panel and **10.06:1** on a raised row; light
    /// `oklch(0.500 0.085 195)` measures **5.20:1** and **4.75:1**. Both clear
    /// their floor (4.5:1 dark, 3:1 light for a non-text element) and neither
    /// clips the sRGB gamut. It is held **1.31:1** dark / **1.37:1** light apart
    /// in luminance from `unmeasured`, the only other cool token, so the two do
    /// not collapse in greyscale.
    ///
    /// Every one of those figures is measured **against the panel**. The
    /// menu-bar mark is drawn on the wallpaper, where no contrast ratio can be
    /// guaranteed against anything — which is exactly why the menu bar carries
    /// this state as a glyph that is *present or absent* and uses colour only as
    /// a second channel. See `KeepAwakeGlyph`.
    public static let awakeNSColor = dynNS(dark: "#51dfdf", light: "#017272")
    public static let awake = Color(nsColor: awakeNSColor)

    /// The tint behind a status pill, and the hairline around it.
    public static func wash(_ tint: Color) -> Color { tint.opacity(0.14) }
    public static func line(_ tint: Color) -> Color { tint.opacity(0.34) }

    // MARK: - Type scale
    //
    // Named by ROLE, never by size, so a size change does not require renaming
    // every call site. Four steps is the whole scale — a status panel that needs
    // more is being over-designed.
    //
    // The floor is 10pt and it is used sparingly. An earlier density pass took
    // secondary text to 10pt and detail to 9pt, which is below every Apple
    // metric (`NSFont.smallSystemFontSize` is 11, `systemFontSize` is 13) and
    // below the readable floor for UI text. Fitting thirteen rows is not worth
    // text nobody can read; the panel scrolls instead.

    /// Panel title.
    public static let titleSize: CGFloat = 13
    /// The account name — the thing being scanned for. Never shrinks.
    public static let bodySize: CGFloat = 13
    /// Percentages, status text, the reset countdown.
    public static let secondaryFontSize: CGFloat = 11
    /// Counters, error detail, pill labels.
    public static let detailFontSize: CGFloat = 10

    public static var titleFont: Font { .system(size: titleSize, weight: .semibold) }
    public static var bodyFont: Font {
        .system(size: bodySize, design: .rounded).weight(.medium)
    }
    public static var secondaryFont: Font { .system(size: secondaryFontSize) }
    public static var detailFont: Font { .system(size: detailFontSize) }
    /// Weight 600 at 10pt. Nothing here goes below 400 — light weights vanish at
    /// UI sizes.
    public static var pillFont: Font {
        .system(size: detailFontSize, weight: .semibold)
    }

    /// Tabular variants. Any value that CHANGES uses one of these: the panel
    /// re-polls every 3 seconds, and proportional digits make percentages and
    /// countdowns jitter their own column on every tick.
    public static var secondaryDigitFont: Font { secondaryFont.monospacedDigit() }
    public static var detailDigitFont: Font { detailFont.monospacedDigit() }
    public static var bodyDigitFont: Font { bodyFont.monospacedDigit() }

    /// Positive tracking for the small pill labels. Small text set tight reads as
    /// crowded; a little air is what makes a 10pt label legible.
    public static let pillTracking: CGFloat = 0.3

    /// Line spacing for text that can wrap to three or more lines. Tight leading
    /// is for one-liners only.
    public static let wrappedLineSpacing: CGFloat = 2

    // MARK: - Space and geometry
    //
    // One 4pt-based ramp instead of scattered magic numbers.

    public static let space1: CGFloat = 2
    public static let space2: CGFloat = 4
    public static let space3: CGFloat = 8
    public static let space4: CGFloat = 12
    public static let space5: CGFloat = 16

    public static let panelWidth: CGFloat = 380
    /// The cap on the scrolling account list — what keeps Quit and the
    /// checkboxes on screen under a long fleet.
    ///
    /// A row count (`visibleAccountRows = 4`) used to do this and was the wrong
    /// unit: rows are not uniform height, so four of them is not a fixed number
    /// of points. `FleetView.visibleRowsHeight(for:)` sums every measured row
    /// and clamps here instead.
    ///
    /// It is the cap on the LIST, not on the panel, and 520 is what it stays: a
    /// header that wraps does not shrink this number, it spends part of it.
    /// The panel is `header + Hairline + list + Hairline + footer`, so a header
    /// line growing from one rendered line to three used to add that height on
    /// top of this cap and push Quit and the checkboxes off the bottom of the
    /// popover. `PanelHeight.listBudget` subtracts the header's overflow from
    /// this cap instead, which is what holds the panel's TOTAL height to what
    /// it was before the spend line existed.
    ///
    /// The number itself lives in `PanelHeight`, with the arithmetic that
    /// reads it, because the test target links `TcrBarCore` and not this one:
    /// stated here, the gate over that arithmetic could only assert against a
    /// hand-copied duplicate and would stay green through any change to it.
    /// It keeps its name over there, and `scripts/tcrbar-palette.py` reads
    /// that file as well as this one, so `--tcr-panel-max-height` is the same
    /// token it always was.
    public static let panelMaxHeight = PanelHeight.panelMaxHeight
    /// The floor under that budget: a header long enough to eat the whole cap
    /// must still leave a list a reader can scroll. A zero-height scroll view
    /// reads as a broken panel, not as a full one. Authored in `PanelHeight`
    /// for the reason above.
    public static let panelMinListHeight = PanelHeight.panelMinListHeight
    public static let gutter = space4
    public static let rowSpacing = space3
    public static let tightSpacing = space2
    /// Gap between lines *inside* a row — tighter than the gap between rows, so
    /// a row still reads as one block.
    public static let rowLineSpacing = space1

    public static let radiusSmall: CGFloat = 4
    public static let radiusMedium: CGFloat = 8
    public static let radiusLarge: CGFloat = 12
    public static let barHeight: CGFloat = 6
    public static let barRadius: CGFloat = 3
    /// Width of a quota bar. Fixed, so the percentage after it starts at the
    /// same x on every card; a bar that took the leftover width could not.
    ///
    /// 72 is what fits. A row has about 300pt, and the 7-day line also carries
    /// `100%` (31), `in 4d 12h` (50) and the Fable weekly window,
    /// `fable 71% · in 4d 12h` (about 105). At 120 the trailing slot rendered
    /// truncated, at 80 it still did on the spent rows. A truncated figure
    /// deletes a measurement; a shorter bar only blunts a magnitude, and 72pt
    /// still resolves under a percent per pixel. The serving counters that used
    /// to hold that slot (`102 req · cache 84%`, 101) are a tooltip now — see
    /// `Account.countersTooltip(countersAreStructural:)`.
    public static let barWidth: CGFloat = 72
    /// Width of the `5h`/`7d` label. `5h` and `7d` are not the same width in a
    /// proportional face, so without this the two bars in a card start a hair
    /// apart.
    public static let windowLabelWidth: CGFloat = 20
    public static let pillRadius = radiusSmall
    public static let pillPaddingH: CGFloat = 6
    public static let pillPaddingV: CGFloat = 2
    public static let hairlineWidth: CGFloat = 0.5

    // MARK: - Motion
    //
    // One duration and one curve for the whole app. A status panel that animates
    // in three different ways is noise, not polish.

    public static let duration: TimeInterval = 0.22
    public static var standardAnimation: Animation {
        .timingCurve(0.22, 1, 0.36, 1, duration: duration)
    }

    // MARK: - Mapping

    public static func color(for state: QuotaState) -> Color {
        switch state {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        }
    }

    public static func color(for kind: FleetTally.Kind) -> Color {
        switch kind {
        case .ok: return ok
        case .near: return near
        case .spent: return spent
        case .unknown: return unknown
        // Reuses `spent`, not a new token: a broken account is known-cannot-
        // serve, the same certainty `spent` already carries, and this repo's
        // colour palette is generated — a new token drags in a regeneration
        // and two blocking gates for a fact this one already covers.
        case .needsRelogin: return spent
        case .unmeasured: return unmeasured
        case .disabled: return disabled
        }
    }

    /// Menu-bar glyph for the fleet's capacity state (`Fleet.capacityGlyphState`).
    /// SF Symbols only, so it renders as a template image and follows the menu
    /// bar's own tint.
    public static func glyph(for state: QuotaState) -> String {
        switch state {
        case .ok: return "gauge.with.dots.needle.33percent"
        case .near: return "gauge.with.dots.needle.67percent"
        case .spent: return "gauge.with.dots.needle.100percent"
        case .unknown: return "questionmark.circle"
        }
    }

    /// Glyph for a state where there is nothing to gauge.
    public static let unreadableGlyph = "exclamationmark.triangle"
}

// MARK: - Hex

extension NSColor {
    /// `#rrggbb`. Token colours are opaque; alpha is applied at the use site so
    /// a wash and its solid parent cannot drift apart.
    fileprivate convenience init(tokenHex hex: String) {
        var s = Substring(hex)
        if s.hasPrefix("#") { s = s.dropFirst() }
        let v = UInt32(s, radix: 16) ?? 0
        self.init(
            srgbRed: CGFloat((v >> 16) & 0xff) / 255,
            green: CGFloat((v >> 8) & 0xff) / 255,
            blue: CGFloat(v & 0xff) / 255,
            alpha: 1
        )
    }
}

// MARK: - Chrome

/// A status pill: a tinted label on a wash of its own hue, with a hairline.
///
/// Copy is stored in natural case and uppercased for display, so a wording change
/// never means rewriting the string, and tracking is applied because small text
/// set tight reads as crowded.
public struct StatusPill: View {
    private let text: String
    private let tint: Color

    public init(_ text: String, tint: Color) {
        self.text = text
        self.tint = tint
    }

    public var body: some View {
        Text(text.uppercased())
            .font(Tok.pillFont)
            .tracking(Tok.pillTracking)
            .foregroundStyle(tint)
            .padding(.horizontal, Tok.pillPaddingH)
            .padding(.vertical, Tok.pillPaddingV)
            .background(
                RoundedRectangle(cornerRadius: Tok.pillRadius)
                    .fill(Tok.wash(tint))
                    .overlay(
                        RoundedRectangle(cornerRadius: Tok.pillRadius)
                            .strokeBorder(Tok.line(tint), lineWidth: Tok.hairlineWidth)
                    )
            )
            .fixedSize()
    }
}

/// One group tag on an account row (``Account/groupTags``) — the whole
/// group-membership UI now that the dedicated Groups tab, deck cards and
/// section headers are gone (bridge: `docs/plans/group-tags-bridge.md`).
///
/// Tinted by the SERVER-resolved colour (``GroupTag/background``), never a
/// colour this app derives itself, so every client agrees on what a group
/// looks like. A missing or malformed colour (`nil`) falls back to
/// ``Tok/inkFaint`` — the same neutral hue ``StatusPill`` and this chip's own
/// prior, uncoloured version both already used — rather than guessing.
///
/// A reserved group is marked with a small lock glyph, not a colour or shape
/// change: colour is already spoken for by group identity here, so a second
/// meaning riding the same channel (filled vs. outlined, a different hue)
/// would ask the reader to disentangle two facts from one visual cue. The
/// glyph is a second, independent channel.
public struct GroupChip: View {
    private let tag: GroupTag

    public init(tag: GroupTag) {
        self.tag = tag
    }

    /// `nil` background (no wire colour) draws the neutral wash a plain
    /// `StatusPill` already uses; a real colour is drawn solid, since a
    /// translucent wash over an operator-chosen hue would mis-render the
    /// luminance ``foreground`` was computed against.
    private var background: Color {
        guard let rgb = tag.background else { return Tok.wash(Tok.inkFaint) }
        return Color(red: rgb.red, green: rgb.green, blue: rgb.blue)
    }

    private var border: Color {
        guard let rgb = tag.background else { return Tok.line(Tok.inkFaint) }
        return Color(red: rgb.red, green: rgb.green, blue: rgb.blue).opacity(0.6)
    }

    /// Chosen from the background's relative luminance
    /// (``GroupTagColor/isLight(_:)``), not hardcoded — these chips sit on a
    /// dark panel and the colour is operator-chosen, so a light pick (a pale
    /// yellow) needs dark text and a very dark pick needs light text, or
    /// either renders unreadable. `nil` background (the neutral fallback)
    /// uses ``Tok/ink``, the panel's own primary-text token, since that wash
    /// is already tuned against the dark panel the same way every other
    /// `StatusPill` is.
    private var foreground: Color {
        guard let rgb = tag.background else { return Tok.ink }
        return GroupTagColor.isLight(rgb) ? .black : .white
    }

    public var body: some View {
        HStack(spacing: 2) {
            if tag.isReserved {
                Image(systemName: "lock.fill")
                    .font(.system(size: Tok.detailFontSize - 2, weight: .bold))
            }
            Text(tag.name.uppercased())
                .font(Tok.pillFont)
                .tracking(Tok.pillTracking)
        }
        .foregroundStyle(foreground)
        .padding(.horizontal, Tok.pillPaddingH)
        .padding(.vertical, Tok.pillPaddingV)
        .background(
            RoundedRectangle(cornerRadius: Tok.pillRadius)
                .fill(background)
                .overlay(
                    RoundedRectangle(cornerRadius: Tok.pillRadius)
                        .strokeBorder(border, lineWidth: Tok.hairlineWidth)
                )
        )
        .fixedSize()
        .help(tag.isReserved ? "\(tag.name) (reserved — held out of the general pool)" : tag.name)
    }
}

/// A 0.5pt hairline. `Divider()` picks up the system separator, which no longer
/// matches this palette's ramp.
public struct Hairline: View {
    public init() {}
    public var body: some View {
        Rectangle()
            .fill(Tok.hairline)
            .frame(height: Tok.hairlineWidth)
    }
}
